# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='assetFunction',
            field=models.ManyToManyField(to='customers.AssetFunction', verbose_name='Function'),
        ),
    ]
