# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20171120_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vertical',
            field=models.ForeignKey(blank=True, help_text='Which industry vertical does the customer belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Vertical'),
        ),
    ]
