# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetdetail',
            options={'ordering': ['assetName']},
        ),
        migrations.RenameField(
            model_name='assetdetail',
            old_name='assetUUID',
            new_name='assetName',
        ),
    ]
