# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20171120_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdetail',
            old_name='assetAttribute',
            new_name='Attribute',
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Asset Name'),
        ),
    ]
