# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20171121_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdetail',
            name='Attribute',
        ),
        migrations.RemoveField(
            model_name='assetdetail',
            name='assetName',
        ),
        migrations.DeleteModel(
            name='AssetDetail',
        ),
    ]
