# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:57
from __future__ import unicode_literals

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20171121_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='accessKey',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
